[build]
  base = "."
  command = "cd bolt && npm install && npm run build"
  publish = "bolt/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.7"
  NPM_FLAGS = "--legacy-peer-deps"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "frame-ancestors 'self'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "autoplay=(), camera=(), geolocation=(self), microphone=()"